### PR TITLE
Python 3.7 compatibility

### PR DESCRIPTION
**Pull request by Chik0**
Renamed async parameter to fix conflict with the keyword

### CODE REVIEW

**Comment by cvinh** [comment]
@jeansch Could you please review that PR ? Thanks in advance

**Comment by nanomishka** [comment]
@jeansch, we are upgrade our python to 3.7 and have problem with this lib. This request solves our problems. Can you merge?

**Comment by jeansch** [comment]
Hi, it would break apps using py-asterisk with python2 and using async.
Can you update your patch to use async_param in python3 and keep async in python2 ?

**Comment by jeansch** [comment]
Closed in #35

**Pull request closed without merging**
